[Service]
MemoryAccounting=yes
MemoryHigh=2G
MemoryMax=3G
MemorySwapMax=0
CPUAccounting=yes
CPUQuota=400%
TasksAccounting=yes
TasksMax=128
LimitNOFILE=8192
OOMPolicy=stop
TimeoutStartSec=180
TimeoutStopSec=45
